"""empty message

Revision ID: 1ea1bfad297b
Revises: 966ff696d38e
Create Date: 2018-01-08 17:57:50.661774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea1bfad297b'
down_revision = '966ff696d38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songrating',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['youtube.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'song_id')
    )
    op.add_column('youtube', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('youtube', sa.Column('type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube', 'type')
    op.drop_column('youtube', 'rating')
    op.drop_table('songrating')
    # ### end Alembic commands ###
