"""youtube table

Revision ID: 966ff696d38e
Revises: 1fd68c648888
Create Date: 2018-01-05 15:43:03.915860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966ff696d38e'
down_revision = '1fd68c648888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sa.String(length=12), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('start_time_seconds', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=8), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_title'), 'youtube', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_title'), table_name='youtube')
    op.drop_table('youtube')
    # ### end Alembic commands ###
